### PR TITLE
Upgrade base to 2.0.0

### PR DESCRIPTION
**Pull request by tei-k**
Updated base version to [2.0.0](https://github.com/Azure/terraform-azurerm-compute/releases/tag/2.0.0)

```
$ git diff upstream/master

diff --git a/main.tf b/main.tf
index 848700b..fd73976 100644
--- a/main.tf
+++ b/main.tf
@@ -1,7 +1,3 @@
-provider "azurerm" {
-  version = ">= 1.1.0"
-}
-
 provider "random" {
   version = "~> 2.1"
 }
@@ -40,7 +36,7 @@ resource "azurerm_virtual_machine" "vm-linux" {
   name                          = "${var.vm_hostname}${count.index}"
   location                      = var.location
   resource_group_name           = azurerm_resource_group.vm.name
-  availability_set_id           = azurerm_availability_set.vm.id
+  availability_set_id           = var.availability_set_id != "" ? var.availability_set_id : azurerm_availability_set.vm.id
   vm_size                       = var.vm_size
   network_interface_ids         = [element(azurerm_network_interface.vm.*.id, count.index)]
   delete_os_disk_on_termination = var.delete_os_disk_on_termination
@@ -58,6 +54,7 @@ resource "azurerm_virtual_machine" "vm-linux" {
     create_option     = "FromImage"
     caching           = "ReadWrite"
     managed_disk_type = var.storage_account_type
+    disk_size_gb      = var.storage_os_disk_size
   }
 
   os_profile {
@@ -89,7 +86,7 @@ resource "azurerm_virtual_machine" "vm-linux-with-datadisk" {
   name                          = "${var.vm_hostname}${count.index}"
   location                      = var.location
   resource_group_name           = azurerm_resource_group.vm.name
-  availability_set_id           = azurerm_availability_set.vm.id
+  availability_set_id           = var.availability_set_id != "" ? var.availability_set_id : azurerm_availability_set.vm.id
   vm_size                       = var.vm_size
   network_interface_ids         = [element(azurerm_network_interface.vm.*.id, count.index)]
   delete_os_disk_on_termination = var.delete_os_disk_on_termination
@@ -107,6 +104,7 @@ resource "azurerm_virtual_machine" "vm-linux-with-datadisk" {
     create_option     = "FromImage"
     caching           = "ReadWrite"
     managed_disk_type = var.storage_account_type
+    disk_size_gb      = var.storage_os_disk_size
   }
 
   storage_data_disk {
@@ -146,7 +144,7 @@ resource "azurerm_virtual_machine" "vm-windows" {
   name                          = "${var.vm_hostname}${count.index}"
   location                      = var.location
   resource_group_name           = azurerm_resource_group.vm.name
-  availability_set_id           = azurerm_availability_set.vm.id
+  availability_set_id           = var.availability_set_id != "" ? var.availability_set_id : azurerm_availability_set.vm.id
   vm_size                       = var.vm_size
   network_interface_ids         = [element(azurerm_network_interface.vm.*.id, count.index)]
   delete_os_disk_on_termination = var.delete_os_disk_on_termination
@@ -164,6 +162,7 @@ resource "azurerm_virtual_machine" "vm-windows" {
     create_option     = "FromImage"
     caching           = "ReadWrite"
     managed_disk_type = var.storage_account_type
+    disk_size_gb      = var.storage_os_disk_size
   }
 
   os_profile {
@@ -189,7 +188,7 @@ resource "azurerm_virtual_machine" "vm-windows-with-datadisk" {
   name                          = "${var.vm_hostname}${count.index}"
   location                      = var.location
   resource_group_name           = azurerm_resource_group.vm.name
-  availability_set_id           = azurerm_availability_set.vm.id
+  availability_set_id           = var.availability_set_id != "" ? var.availability_set_id : azurerm_availability_set.vm.id
   vm_size                       = var.vm_size
   network_interface_ids         = [element(azurerm_network_interface.vm.*.id, count.index)]
   delete_os_disk_on_termination = var.delete_os_disk_on_termination
@@ -207,6 +206,7 @@ resource "azurerm_virtual_machine" "vm-windows-with-datadisk" {
     create_option     = "FromImage"
     caching           = "ReadWrite"
     managed_disk_type = var.storage_account_type
+    disk_size_gb      = var.storage_os_disk_size
   }
 
   storage_data_disk {
@@ -294,4 +294,4 @@ resource "azurerm_network_interface" "vm" {
   }
 
   tags = var.tags
-}
\ No newline at end of file
+}
diff --git a/outputs.tf b/outputs.tf
index 0964ea5..3282d6b 100644
--- a/outputs.tf
+++ b/outputs.tf
@@ -40,5 +40,5 @@ output "public_ip_dns_name" {
 
 output "availability_set_id" {
   description = "id of the availability set where the vms are provisioned."
-  value       = "${azurerm_availability_set.vm.id}"
+  value       = "${var.availability_set_id != "" ? var.availability_set_id : azurerm_availability_set.vm.id }"
 }
diff --git a/variables.tf b/variables.tf
index 396f734..0d70a6d 100644
--- a/variables.tf
+++ b/variables.tf
@@ -158,3 +158,12 @@ variable "enable_accelerated_networking" {
   description = "(Optional) Enable accelerated networking on Network interface"
   default     = false
 }
+
+variable "storage_os_disk_size" {
+  description = "Defines the size of the OS disk"
+  default     = "64"
+}
+
+variable "availability_set_id" {
+  default = ""
+}
```

### CODE REVIEW

**Review by feeblefakie — APPROVED** [review]
LGTM ! (but not really sure to be honest)

**Comment by ymorimo** [comment]
@tei-k I think what we need to do is `git merge upstream/master` so that we can record that we catched up our fork to the upstream (`Azure/terraform-azurerm-compute`).
The above merge command results in a conflicting state in main.tf, and it means that the change you need to resolve it is equivalent to what we have changed in our fork.

**Comment by tei-k** [comment]
@ymorimo 

Thanks! I merged tag 2.0.0 and Resolved conflicting.
(メジャーバージョンアップだったので2.0.0上に直接修正をして使ってたのが原因ですね 👍)

**Review by ymorimo — APPROVED** [review]
LGTM 🙆‍♂️

**Pull request merged**
